### PR TITLE
Fix Issue #330

### PR DESCRIPTION
**Pull request by soegaard**
Ignore non-valid unicode characters.

### CODE REVIEW

**Comment by mflatt** [comment]
I imagine these values are generated for characters in supplementary planes. Should input handling track surrogate pairs and join them to form those characters?

**Comment by lambduli** [comment]
@soegaard I have just tried out all the characters in my custom layout. Everything works exactly as I would expect.

As per dead keys — my custom layout doesn't have any. (But my standard Czech layout has two and those work just fine in DrRacket.)

**Comment by soegaard** [comment]
@lambduli Thanks for the report.

@mflatt Since Jan is the only one that come across the problem, and his layout seems to work,
I am inclined to keep the PR as-is.

**Comment by mflatt** [comment]
I don't think the bits described in the quoted documentation are the relevant ones. Those seem maybe part of a `uchr` resource.

Meanwhile, the result is a `UniChar` array, which is UTF-16, and characters like '𝔸' need surrogate encoding in UTF-16. I think the right change is

```
(define output-chars (malloc _UniChar (add1 max-string-length))) ; leave room for a terminator
```
and then
```
  ;; get the number of characters returned, and convert to string;
  ;; the characters are UTF-16
  (define n (max 0 (min max-string-length (unbox actual-string-length))))
  (ptr-set! output-chars _UniChar (add1 n) 0) ; ensure nul terminator
  (cast output-chars _pointer _string/utf-16))
```

**Comment by soegaard** [comment]
Your solution certainly looks better.
I tested it and it works for me.

@lambduli Can you change this last version?

Around line 483 the code now looks like this:

```
  (UCKeyTranslate layout 
                  virtual-key-code
                  key-action
                  (bitwise-and (>> modifier-key-state 8) #xFF)
                  keyboard-type
                  key-translate-options
                  dead-key-state
                  max-string-length
                  actual-string-length
                  output-chars)
  ;; get the number of characters returned, and convert to string;
  ;; the characters are UTF-16
  (define n (max 0 (min max-string-length (unbox actual-string-length))))
  (ptr-set! output-chars _UniChar n 0) ; ensure nul terminator
  (cast output-chars _pointer _string/utf-16))
```

And in line 429 an `add1` was added:
```
(define output-chars (malloc _UniChar (add1 max-string-length))) ; leave room for a terminator
```

**Comment by lambduli** [comment]
Hi @soegaard, I am sorry for such a long delay! I had to take time off because of some deadlines and such.

I am happy to try that change.
So I replaced the code that began at line 483 with the new one (rewriting the few lines that featured the original fix from #330).

I also replaced the 429th line.

I tried to run DrRacket and it launched fine it also seems that all my special characters work in the editor just fine.

**Comment by mflatt** [comment]
Closing as fixed by #334.

**Pull request closed without merging**
