### PR TITLE
update gtk icon apis and stock file names per the gtk doc

### LINKED ISSUE #267: GTK warnings when running slideshow programs on wayland Gnome 42
The program I ran:
```
#lang slideshow ; or slideshow/widescreen

(slide
 #:title "How to Say Hello"
 (t "Hello World!"))
```

warnings:

```
(main.rkt:5079): Gtk-WARNING **: 14:35:00.915: Error loading theme icon 'dialog-warning' for stock: Icon 'dialog-warning' not present in theme Adwaita

(main.rkt:5079): Gtk-WARNING **: 14:35:00.930: Error loading theme icon 'dialog-warning' for stock: Icon 'dialog-warning' not present in theme Adwaita

(main.rkt:5079): Gtk-WARNING **: 14:35:00.950: Error loading theme icon 'dialog-warning' for stock: Icon 'dialog-warning' not present in theme Adwaita

(main.rkt:5079): Gtk-WARNING **: 14:35:00.981: Error loading theme icon 'dialog-warning' for stock: Icon 'dialog-warning' not present in theme Adwaita
```

I didn't get those warnings when I was on gnome 41

### PR DESCRIPTION
**Pull request by capfredf**
closes #267

### CODE REVIEW

**Comment by capfredf** [comment]
cf. https://docs.gtk.org/gtk3/const.STOCK_DIALOG_WARNING.html, https://docs.gtk.org/gtk3/ctor.Image.new_from_stock.html

**Comment by mflatt** [comment]
It looks like the new function is available since Gtk 2.6. That seems far back, but I can't remember how old we try to support. Does it seem safe to merge without a fallback that uses the old name?

**Comment by capfredf** [comment]
Since Gtk 3.10 was released in 2013 and is not maintained any more, I think it is safe to use the new file names without fallbacks.

**Comment by rfindler** [comment]
2013 doesn't sound that old but I think that maybe is saying something about me more than about this change ;)

**Comment by mflatt** [comment]
As far as I can tell, version 2.6 really is old (a lot older than 2013), so this change seems ok to merge.

**Pull request merged**
