### PR TITLE
Changes a 'than' to 'then' in win-overview-scrbl

### PR DESCRIPTION
**Pull request by jerry-james**

### CODE REVIEW

**Comment by jbclements** [comment]
thanks!

**Comment by stamourv** [comment]
@jbclements: Did you forget to push the change?

**Comment by jbclements** [comment]
Ah... I see... I neglected to click the "confirm merge" button. Hopefully it's good now... sigh.

**Comment by rfindler** [comment]
@jbclements Please don't push the "merge" button unless there really is a reason to think of this as two parallel development lines. Instead, you can push one of the other buttons to make it appear just like the latest commit.

**Comment by jbclements** [comment]
> On Dec 2, 2016, at 18:42, Robby Findler <notifications@github.com> wrote:
> 
> @jbclements Please don't push the "merge" button unless there really is a reason to think of this as two parallel development lines. Instead, you can push one of the other buttons to make it appear just like the latest commit.

Please forgive me. My good command-line habits (always rebase before push) abandoned me in the presence of the shiny gui buttons.

John

**Comment by rfindler** [comment]
Shiny buttons!! :)

**Pull request merged**
