### PR TITLE
Added alpha-channel to paste from clipboard

### PR DESCRIPTION
**Pull request by Kalimehtar**
Fixes https://github.com/racket/racket/issues/2273

### CODE REVIEW

**Comment by Kalimehtar** [comment]
What is wrong with my propose? No merge, no comments. Why?

**Comment by mflatt** [comment]
Apologies – I did lose track of this. I hope to take a look in the next couple of days and either merge (seems likely) or provide feedback.

**Comment by mflatt** [comment]
Thank you very much for the patch!

I get a mangled image when I try to copy from Edge. It looks like Edge creates a 24-bit image (with no alpha channel) for `CF_DIBV5`, so parsing the data as a 32-bit image goes wrong.

One possibility is to pay attention to the `biBitCount` field when parsing the image. Another possibility is to use the `CF_DIBV5` data only when it is a 32-bit image, and otherwise use the other formats. I'd go with the second option, unless there's some advantage to `CF_DIBV5` besides an alpha channel. If that sounds like a good idea to you, can you make that change, and then I'll merge?

**Comment by Kalimehtar** [comment]
> Another possibility is to use the CF_DIBV5 data only when it is a 32-bit image, and otherwise use the other formats.

I added the check.

**Pull request merged**
